// ========== CHAPTER 2: 捜査 ==========
const Chapter2 = {
  scenes: {

    // ===== 場面1：日曜朝 — 山本との密会（カフェ） =====
    ch2_scene1: {
      chapterTitle: '第2章',
      chapterSub: '捜　　査',
      location: 'カフェ「GRAIN」',
      time: '日曜日 9:00',
      bg: 'bg-cafe',
      content: [
        { type: 'narration', text: '日曜の朝。\n駅前のカフェに山本を呼び出した。' },
        { type: 'narration', text: '店内は休日の穏やかな空気に包まれている。\nだが自分の胸の中は嵐だ。' },
        { type: 'narration', text: '山本が来た。\n顔色が悪い。目の下にくまがある。\n昨夜は眠れなかったのだろう。' },
        { type: 'text', speaker: '山本', text: '……来てくれたか。' },
        { type: 'text', speaker: '{name}', text: 'ああ。話がある{nda}ろ。' },
        { type: 'narration', text: '山本はコーヒーカップを両手で握りしめながら\n周囲を何度も確認した。' },
        { type: 'text', speaker: '山本', text: '田中のこと…俺、知ってることがある。\nでも話したら…俺も危ないかもしれない。' },
        { type: 'text', speaker: '{name}', text: '……何を知ってるんだ。' },
        { type: 'narration', text: '山本が声を落とした。' },
        { type: 'text', speaker: '山本', text: '田中は…会社の経理で不正を見つけたんだ。\n架空の取引。数千万円規模の。' },
        { type: 'effect', name: 'shake' },
        { type: 'text', speaker: '山本', text: 'そしてその不正に…\n佐藤部長が関わっている。' },
        { type: 'sfx', name: 'tensionSting' },
        { type: 'narration', text: '佐藤部長。\nあの妙に冷静だった男。\n「余計なことを言うな」と言った男。' },
        {
          type: 'evidence',
          id: 'yamamoto_testimony',
          name: '山本の証言',
          description: '「田中は経理の不正を発見した。佐藤部長が関わっている」という山本の証言。',
        },
        { type: 'text', speaker: '{name}', text: '……それを、どこまで確かめた。' },
        { type: 'text', speaker: '山本', text: '田中本人から聞いた。\n殺される1週間前に。\n「やばいものを見つけた」って。\nそれ以上は教えてくれなかったけど。' },
        {
          type: 'evidence',
          id: 'tanaka_trouble',
          name: '田中が「会社でやばいこと」を発見した証言',
          description: '山本経由。田中は殺される1週間前に「やばいものを見つけた」と語っていた。',
        },
        { type: 'narration', text: '田中は不正を見つけた。\nだから殺された。\n\nそして自分は、犯人に仕立て上げられようとしている。' },
      ],
      choices: [
        {
          id: 'cooperate',
          text: '「一緒に調べてくれ」',
          params: { boldness: 2 },
          flags: { ch2_scene1_choice: 'cooperate', yamamoto_ally: true },
          next: 'ch2_scene1_cooperate',
        },
        {
          id: 'info_only',
          text: '「情報だけでいい。巻き込みたくない」',
          params: { investigation: 2 },
          flags: { ch2_scene1_choice: 'info_only' },
          next: 'ch2_scene1_info_only',
        },
        {
          id: 'tell_kuroda',
          text: '「黒田刑事に全部話そう」',
          params: { trust: 2 },
          flags: { ch2_scene1_choice: 'tell_kuroda' },
          next: 'ch2_scene1_tell_kuroda',
        },
      ],
    },

    ch2_scene1_cooperate: {
      location: 'カフェ「GRAIN」',
      time: '日曜日 9:30',
      bg: 'bg-cafe',
      showTransition: false,
      content: [
        { type: 'text', speaker: '{name}', text: '山本、頼む。\n一人じゃどうにもならない{nda}。\n一緒に調べてくれ。' },
        { type: 'narration', text: '山本は長い間黙っていた。\nコーヒーが冷めていく。' },
        { type: 'text', speaker: '山本', text: '……わかった。\n俺も、田中のこと放っておけない。' },
        { type: 'narration', text: '山本の目に覚悟が宿った。\n心強い味方を得た。' },
        { type: 'text', speaker: '山本', text: '田中のデスクに何か残ってるかもしれない。\n今日は日曜だ。オフィスには誰もいないはず。' },
        { type: 'text', speaker: '{name}', text: '……忍び込むのか。' },
        { type: 'text', speaker: '山本', text: 'ああ。俺が警備のシフトを確認する。\n午後なら行けるはずだ。' },
      ],
      next: 'ch2_scene2',
    },

    ch2_scene1_info_only: {
      location: 'カフェ「GRAIN」',
      time: '日曜日 9:30',
      bg: 'bg-cafe',
      showTransition: false,
      content: [
        { type: 'text', speaker: '{name}', text: '情報だけでいい。\nお前を巻き込みたくない。' },
        { type: 'text', speaker: '山本', text: '……わかった。\nでも一つだけ。' },
        { type: 'text', speaker: '山本', text: '田中のデスク。\nあいつ、何かをUSBに保存してた。\n「保険だ」って言ってた。' },
        { type: 'narration', text: 'USBメモリ。\nそれが今も田中のデスクにあるなら──' },
        { type: 'text', speaker: '{name}', text: 'わかった。\n自分でなんとかする。' },
        { type: 'text', speaker: '山本', text: '……気をつけろよ。' },
      ],
      next: 'ch2_scene2',
    },

    ch2_scene1_tell_kuroda: {
      location: 'カフェ「GRAIN」',
      time: '日曜日 9:30',
      bg: 'bg-cafe',
      showTransition: false,
      content: [
        { type: 'text', speaker: '{name}', text: '黒田刑事に全部話そう。\n警察に任せるべきだ。' },
        { type: 'text', speaker: '山本', text: '……大丈夫か？\n佐藤は会社じゃ力がある。\n警察にも知り合いがいるかもしれない。' },
        { type: 'text', speaker: '{name}', text: '黒田は信用できると思う。\nあの目は本物だ。' },
        { type: 'text', speaker: '山本', text: 'わかった。\nでも全部は話さないでくれ。\n俺の名前は出さないで。' },
        { type: 'narration', text: '山本の恐怖は本物だ。\n黒田に伝えるにしても、まずは証拠が必要だ。' },
        { type: 'text', speaker: '山本', text: 'それと…田中のデスクにUSBがあるかもしれない。\n「保険」だって言ってた。' },
      ],
      next: 'ch2_scene2',
    },

    // ===== 場面2：日曜昼 — 会社に忍び込む（ステルスアクション） =====
    ch2_scene2: {
      location: '□□商事 本社ビル',
      time: '日曜日 13:00',
      bg: 'bg-office-dark',
      content: [
        { type: 'narration', text: '日曜の午後。\n会社のビルは静まり返っている。' },
        { type: 'narration', text: '社員証で入館ゲートを通る。\n休日出勤は珍しくない。\nここまでは怪しまれない。' },
        { type: 'narration', text: 'だが田中のデスクがある経理部フロアは\n警備員が巡回している。' },
        { type: 'narration', text: '非常階段から3階へ。\nドアをそっと開ける。' },
        { type: 'sfx', name: 'doorCreak' },
        { type: 'narration', text: '薄暗いオフィス。\n非常灯の緑色の光だけが\n廊下を照らしている。' },
        { type: 'narration', text: '田中のデスクまでたどり着けるか──' },
      ],
      choices: [
        {
          id: 'observe',
          text: '警備員の巡回パターンを観察してから進む',
          params: { investigation: 2 },
          flags: { stealth_success: true },
          next: 'ch2_scene2_step2',
        },
        {
          id: 'rush',
          text: '今のうちに急いで駆け抜ける',
          params: { suspicion: 2 },
          flags: { stealth_success: false },
          next: 'ch2_scene2_fail',
        },
        {
          id: 'distract',
          text: '物音を立てて警備員をおびき寄せ、隙に進む',
          params: { boldness: 1, investigation: 1 },
          flags: { stealth_success: true },
          next: 'ch2_scene2_step2',
        },
      ],
      timeLimit: 10,
    },

    // ===== ステルス第2段階 — オフィス内移動 =====
    ch2_scene2_step2: {
      location: '□□商事 経理部フロア',
      time: '日曜日 13:10',
      bg: 'bg-office-dark',
      showTransition: false,
      content: [
        { type: 'narration', text: '経理部フロアに入った。\n非常灯の薄緑の光だけが頼りだ。' },
        { type: 'narration', text: '田中のデスクは奥の窓際。\nあと十数メートル──' },
        { type: 'sfx', name: 'footsteps' },
        { type: 'narration', text: '足音！\nエレベーターが動いている。\n誰かが上がってくる。' },
      ],
      choices: [
        {
          id: 'hide_desk',
          text: '近くのデスクの下に隠れる',
          params: { investigation: 1 },
          next: 'ch2_scene2_step2_hide',
        },
        {
          id: 'rush_tanaka',
          text: '今のうちに田中のデスクまで走る',
          params: { boldness: 1 },
          next: 'ch2_scene2_step2_rush',
        },
      ],
      timeLimit: 6,
    },

    ch2_scene2_step2_hide: {
      location: '□□商事 経理部フロア',
      time: '日曜日 13:12',
      bg: 'bg-office-dark',
      showTransition: false,
      content: [
        { type: 'narration', text: 'デスクの下に身を縮める。\n心臓の音が聞こえるほどの静寂。' },
        { type: 'sfx', name: 'footsteps' },
        { type: 'narration', text: '足音が近づき──通り過ぎた。\n清掃員だ。別のフロアに向かったようだ。' },
        { type: 'narration', text: '息を吐く。\n今のうちに田中のデスクへ急ぐ。' },
      ],
      next: 'ch2_scene2_success',
    },

    ch2_scene2_step2_rush: {
      location: '□□商事 経理部フロア',
      time: '日曜日 13:12',
      bg: 'bg-office-dark',
      showTransition: false,
      content: [
        { type: 'narration', text: '暗闇の中を走る。\n椅子にぶつかりそうになりながら──' },
        { type: 'narration', text: '着いた。田中のネームプレート。\nエレベーターの音は…止んだ。\n別の階で降りたようだ。' },
        { type: 'narration', text: '助かった。時間がない。急いで調べよう。' },
      ],
      next: 'ch2_scene2_success',
    },

    ch2_scene2_success: {
      location: '□□商事 経理部フロア',
      time: '日曜日 13:15',
      bg: 'bg-office-dark',
      showTransition: false,
      content: [
        { type: 'narration', text: '警備員をやり過ごし、田中のデスクにたどり着いた。' },
        { type: 'narration', text: '引き出しを開ける。\nファイルの下に──あった。' },
        { type: 'narration', text: 'USBメモリ。\nラベルには手書きで\n「sato_keiri_2024」と書かれている。' },
        {
          type: 'evidence',
          id: 'usb_memory',
          name: 'USBメモリ「sato_keiri_2024」',
          description: '田中のデスクの引き出しに隠されていたUSBメモリ。ラベルに「sato_keiri_2024」と書かれている。',
        },
        { type: 'narration', text: '佐藤の経理データ。\n田中が言っていた「保険」はこれだ。' },
        { type: 'narration', text: 'さらに引き出しの奥に\n小さな金庫が見える。\nダイヤル式のロックがかかっている。' },
        { type: 'narration', text: '金庫の表面にメモが貼ってある。\n「0714を思い出せ」\n\n……逆から読むのか？' },
        {
          type: 'puzzle',
          id: 'safe_code',
          question: '佐藤の金庫のロック解除',
          clues: [
            'メモ: 「0714を思い出せ」',
            '数字を逆順に並べ替えよ',
          ],
          answer: '4170',
          hints: [
            '0714を逆に読むと？',
            '4-1-7-0 → 4170',
          ],
          wrongMessage: 'ダイヤルが回らない…もう一度考えよう',
          evidence: [
            { id: 'intruder_watch', name: '侵入者の高級腕時計の目撃', description: '金庫の中にあった写真。高級腕時計をした人物が田中と会っている。' },
          ],
          params: { investigation: 2 },
          flags: { safe_opened: true },
        },
        { type: 'narration', text: '金庫が開いた。\n中には写真と領収書が入っている。' },
        {
          type: 'evidence',
          id: 'thursday_dinner',
          name: '田中と佐藤の木曜の食事',
          description: '田中のデスクの引き出しに入っていた領収書。殺害前日の木曜、高級レストランで佐藤と2人で食事。',
        },
        { type: 'narration', text: '木曜日の日付。高級レストラン。\n「2名様」。\n殺される前日に、田中は佐藤と食事をしていた。' },
        { type: 'narration', text: '急いでポケットにねじ込み、来た道を戻る。\n誰にも見つからなかった。' },
      ],
      next: 'ch2_scene3',
    },

    ch2_scene2_fail: {
      location: '□□商事 本社ビル 1階',
      time: '日曜日 13:15',
      bg: 'bg-office-dark',
      showTransition: false,
      content: [
        { type: 'narration', text: '物音を立ててしまった。\n警備員がこちらに気づいた。' },
        { type: 'text', speaker: '警備員', text: 'おい、誰だ！\n……あんた、社員か？' },
        { type: 'text', speaker: '{name}', text: 'す、すみません。\n忘れ物を取りに来たんですが\n暗くてつまずいて…' },
        { type: 'text', speaker: '警備員', text: '休日は事前申請が必要ですよ。\n名前と所属を記録させてください。' },
        { type: 'narration', text: 'しぶしぶ記録される。\nこの記録が後から問題にならなければいいが。' },
        { type: 'narration', text: '田中のデスクには近づけなかった。\nだがここで諦めるわけにはいかない。' },
        {
          type: 'condition',
          condition: { flag: 'yamamoto_ally', value: true },
          then: 'ch2_scene2_fail_yamamoto',
          else: 'ch2_scene2_fail_solo',
        },
      ],
    },

    ch2_scene2_fail_yamamoto: {
      location: '—',
      time: '日曜日 14:00',
      bg: 'bg-cafe',
      showTransition: false,
      content: [
        { type: 'narration', text: '山本に連絡した。' },
        { type: 'text', speaker: '山本', text: '見つかったのか…\nわかった。俺が明日、別の方法で\n田中のデスクを調べてみる。' },
        { type: 'narration', text: '翌日、山本からメッセージが届いた。' },
        {
          type: 'phone',
          appName: '山本とのトーク',
          messages: [
            { from: 'other', text: 'USBあった。田中の引き出しの奥。', time: '月曜 8:30', senderName: '山本' },
            { from: 'other', text: 'ラベルに「sato_keiri_2024」って書いてある', time: '月曜 8:31', senderName: '山本' },
            { from: 'other', text: 'あと領収書も。木曜日のレストラン。佐藤と2名で。', time: '月曜 8:32', senderName: '山本' },
            { from: 'player', text: 'ありがとう。今夜会えるか', time: '月曜 8:35' },
          ],
        },
        {
          type: 'evidence',
          id: 'usb_memory',
          name: 'USBメモリ「sato_keiri_2024」',
          description: '田中のデスクの引き出しに隠されていたUSBメモリ。山本が回収。ラベルに「sato_keiri_2024」と書かれている。',
        },
        {
          type: 'evidence',
          id: 'thursday_dinner',
          name: '田中と佐藤の木曜の食事',
          description: '田中のデスクにあった領収書。殺害前日の木曜、高級レストランで佐藤と2人で食事。',
        },
      ],
      next: 'ch2_scene3',
    },

    ch2_scene2_fail_solo: {
      location: '自宅',
      time: '日曜日 14:00',
      bg: 'bg-home-morning',
      showTransition: false,
      content: [
        { type: 'narration', text: '一旦引き下がる。\n別の方法を考えなければ。' },
        { type: 'narration', text: '夜になって、思い切って\n同僚の鈴木に連絡してみた。\n田中と一番仲が良かった男だ。' },
        {
          type: 'phone',
          appName: '鈴木とのトーク',
          messages: [
            { from: 'player', text: '突然すまない。田中のことで聞きたいことがある', time: '20:00' },
            { from: 'other', text: '…田中のこと？', time: '20:05', senderName: '鈴木' },
            { from: 'player', text: '田中のデスクにUSBがないか確認できないか', time: '20:06' },
            { from: 'other', text: 'わかった。明日見てみる', time: '20:10', senderName: '鈴木' },
          ],
        },
        { type: 'narration', text: '翌朝、鈴木からUSBメモリと領収書の写真が送られてきた。' },
        {
          type: 'evidence',
          id: 'usb_memory',
          name: 'USBメモリ「sato_keiri_2024」',
          description: '田中のデスクの引き出しに隠されていたUSBメモリ。鈴木が写真を撮影。ラベルに「sato_keiri_2024」と書かれている。',
        },
        {
          type: 'evidence',
          id: 'thursday_dinner',
          name: '田中と佐藤の木曜の食事',
          description: '田中のデスクにあった領収書。殺害前日の木曜、高級レストランで佐藤と2人で食事。',
        },
      ],
      next: 'ch2_scene3',
    },

    // ===== 場面3：日曜夕方 — 鈴木の証言 =====
    ch2_scene3: {
      location: '公園のベンチ',
      time: '日曜日 17:00',
      bg: 'bg-home-evening',
      content: [
        { type: 'narration', text: '同僚の鈴木と会うことにした。\n田中と一番仲が良かった男だ。' },
        { type: 'narration', text: '夕暮れの公園。\n人気のないベンチに二人で座る。' },
        { type: 'text', speaker: '鈴木', text: '……田中のこと、まだ信じられないよ。' },
        { type: 'text', speaker: '{name}', text: '鈴木。田中のことで聞きたいことがある。\n最近の田中の様子、何か気づいたことはないか。' },
        { type: 'narration', text: '鈴木は少し考えてから口を開いた。' },
        { type: 'text', speaker: '鈴木', text: '最後の1〜2週間は\n明らかに様子がおかしかった。\nいつもビクビクしてた。' },
        { type: 'text', speaker: '鈴木', text: 'それと…佐藤部長と\nやたら2人で話してたんだ。\n会議室で。ドア閉めて。' },
        { type: 'text', speaker: '鈴木', text: 'あと一度、田中が電話してるのを聞いた。\n「もうやめてくれ」って。\n相手は…わからない。' },
        { type: 'text', speaker: '鈴木', text: 'そういえば最近、\n田中のところに女の人が\n訪ねてきてたこともあった。\n会社の別の部署の人だと思うけど…' },
        {
          type: 'evidence',
          id: 'suzuki_witness',
          name: '鈴木の目撃証言',
          description: '田中は最後の2週間、怯えていた。佐藤部長と頻繁に2人で密会。「もうやめてくれ」と電話していた。',
        },
        { type: 'narration', text: '鈴木の証言は山本の話と一致する。\n田中は不正を見つけ、佐藤に追い詰められていた。' },
      ],
      choices: [
        {
          id: 'tell_all',
          text: '鈴木に全てを打ち明ける',
          params: { trust: 1, boldness: 1 },
          flags: { ch2_scene3_choice: 'tell_all', suzuki_ally: true },
          next: 'ch2_scene3_tell_all',
        },
        {
          id: 'hide_core',
          text: '核心は隠しておく',
          params: { investigation: 1 },
          flags: { ch2_scene3_choice: 'hide' },
          next: 'ch2_scene3_hide',
        },
      ],
    },

    ch2_scene3_tell_all: {
      location: '公園のベンチ',
      time: '日曜日 17:30',
      bg: 'bg-home-evening',
      showTransition: false,
      content: [
        { type: 'text', speaker: '{name}', text: '鈴木…実は{I}、今こういう状況にいる。' },
        { type: 'narration', text: '偽造メッセージのこと。\n脅迫のこと。\n佐藤の不正のこと。\n全て打ち明けた。' },
        { type: 'text', speaker: '鈴木', text: '……マジかよ。\nお前、ハメられてるのか。' },
        { type: 'text', speaker: '鈴木', text: '佐藤部長が…\nいや、あの人ならやりかねない。\n社内での権力の使い方、異常だったからな。' },
        { type: 'text', speaker: '鈴木', text: '何かあったら俺に言えよ。\n田中の分まで、俺にできることはする。' },
        { type: 'narration', text: '鈴木が味方についた。\n田中のためにも、真相を暴く。' },
      ],
      next: 'ch2_scene4',
    },

    ch2_scene3_hide: {
      location: '公園のベンチ',
      time: '日曜日 17:30',
      bg: 'bg-home-evening',
      showTransition: false,
      content: [
        { type: 'text', speaker: '{name}', text: 'ありがとう。参考になった。\nもし他に何か思い出したら教えてくれ。' },
        { type: 'text', speaker: '鈴木', text: '……お前、何か隠してないか？' },
        { type: 'narration', text: '鈴木の目が鋭くなった。' },
        { type: 'text', speaker: '{name}', text: 'いや…ただ、田中のことが気になって。' },
        { type: 'text', speaker: '鈴木', text: '……そうか。\nまあ、何かあったら連絡くれ。' },
        { type: 'narration', text: '鈴木は少し距離を置いたようだった。\nこれ以上は踏み込んでこないだろう。' },
      ],
      next: 'ch2_scene4',
    },

    // ===== 場面4：日曜夜 — USBメモリの中身 =====
    ch2_scene4: {
      location: '自宅',
      time: '日曜日 22:00',
      bg: 'bg-home-evening',
      content: [
        { type: 'narration', text: '自宅に戻り、パソコンを開いた。' },
        { type: 'narration', text: 'USBメモリを差し込む。\nパスワードが要求された。' },
        { type: 'narration', text: '田中のデスクに貼ってあったメモを思い出す。\n「1, 1, 2, 3, 5, ?」\n\n何かの数列のようだ。' },
        {
          type: 'puzzle',
          id: 'usb_password',
          question: 'USBメモリのパスワード',
          clues: [
            '数列: 1, 1, 2, 3, 5, ?',
            '次の数字を入力せよ',
          ],
          answer: '8',
          hints: [
            'フィボナッチ数列：前の2つの数字を足すと次の数字になる',
            '3 + 5 = ?',
          ],
          wrongMessage: 'パスワードが違う…数列を解読しよう',
          params: { investigation: 1 },
        },
        { type: 'narration', text: 'ロックが解除された。\n中身は一つのフォルダ。「経理データ」。' },
        { type: 'narration', text: 'Excelファイルが数十個。\n開いてみると──' },
        { type: 'effect', name: 'shake' },
        { type: 'narration', text: '架空取引の帳簿だ。\n存在しない会社への発注書。\n水増しされた経費精算。' },
        { type: 'narration', text: '金額を足していく。\n3000万…5000万……\n合計で7000万円を超えている。' },
        { type: 'sfx', name: 'tensionSting' },
        { type: 'narration', text: '全てのファイルに佐藤の承認印がある。\nこれは決定的な証拠だ。' },
        { type: 'narration', text: '田中はこれを見つけた。\nだから殺された。' },
        { type: 'narration', text: 'もう一つフォルダがある。\n「diary」と名付けられた日記。' },
        { type: 'narration', text: '最後の日記は殺される3日前。\n「中村さんを巻き込むわけにはいかない」\n\n……中村？\n誰だ。' },
        { type: 'narration', text: '田中のデスクにあった脅迫メールの\nプリントアウトも見つかった。\n差出人は「野口健二」。' },
        { type: 'narration', text: '「お前のせいで俺の人生は終わった。\n覚えていろ」' },
        {
          type: 'evidence',
          id: 'noguchi_threat_email',
          name: '野口から田中への脅迫メール',
          description: '解雇された元社員・野口健二から田中への脅迫メール。「お前のせいで俺の人生は終わった。覚えていろ」',
        },
        {
          type: 'evidence',
          id: 'sato_embezzlement',
          name: '佐藤の横領データ',
          description: 'USBメモリの中身。架空取引の帳簿データ。佐藤の承認印入り。総額7000万円超の横領の証拠。',
        },
        { type: 'narration', text: 'その時、スマホが鳴った。' },
        { type: 'sfx', name: 'phoneRing' },
        { type: 'narration', text: '画面に表示された名前は──「佐藤部長」。' },
        { type: 'effect', name: 'shake' },
        { type: 'narration', text: '今、このタイミングで佐藤から？\n偶然か。それとも……' },
      ],
      choices: [
        {
          id: 'answer',
          text: '電話に出る',
          params: { boldness: 2 },
          flags: { ch2_scene4_choice: 'answer' },
          next: 'ch2_scene4_answer',
        },
        {
          id: 'ignore',
          text: '無視する',
          params: { investigation: 1 },
          flags: { ch2_scene4_choice: 'ignore' },
          next: 'ch2_scene4_ignore',
        },
        {
          id: 'record',
          text: '録音アプリを起動してから出る',
          params: { investigation: 3 },
          flags: { ch2_scene4_choice: 'record' },
          evidence: [{ id: 'sato_call_record', name: '佐藤との通話録音', description: '日曜夜の佐藤からの電話を録音。佐藤は「最近どうだ」と探りを入れてきた。声には余裕があった。' }],
          next: 'ch2_scene4_record',
        },
      ],
      timeLimit: 8,
    },

    ch2_scene4_answer: {
      location: '自宅',
      time: '日曜日 22:15',
      bg: 'bg-home-evening',
      showTransition: false,
      content: [
        { type: 'text', speaker: '{name}', text: '……もしもし。' },
        { type: 'text', speaker: '佐藤', text: 'おう、{name}。夜遅くにすまんな。\n田中のことで色々大変だろう。\n体は大丈夫か？' },
        { type: 'narration', text: 'あの冷たい声が耳に刺さる。\n心配しているふりか。' },
        { type: 'text', speaker: '佐藤', text: '警察にはもう何度か話を聞かれたか？\nまあ、余計なことは言わなくていい。\n会社のことは会社で処理するから。' },
        { type: 'narration', text: '「余計なことは言うな」。\nまたこのセリフだ。\n\n佐藤は自分が何を知っているか\n探ろうとしている。' },
        { type: 'text', speaker: '{name}', text: '……はい、大丈夫です。' },
        { type: 'text', speaker: '佐藤', text: 'そうか。何かあったら言えよ。\nじゃあな。' },
        { type: 'narration', text: '通話が切れた。\n手が震えている。\n\nあの男は、どこまで知っているんだ。' },
      ],
      next: 'ch2_scene5_noguchi',
    },

    ch2_scene4_ignore: {
      location: '自宅',
      time: '日曜日 22:15',
      bg: 'bg-home-evening',
      showTransition: false,
      content: [
        { type: 'narration', text: '電話に出なかった。\n今、佐藤と話すのは危険だ。\n声に動揺が出るかもしれない。' },
        { type: 'narration', text: '着信は30秒ほどで切れた。\n留守電も残されていない。' },
        { type: 'narration', text: '佐藤は何が目的だったのか。\n様子を探ろうとしていたのか。\n\n……警戒を強めなければ。' },
      ],
      next: 'ch2_scene5_noguchi',
    },

    ch2_scene4_record: {
      location: '自宅',
      time: '日曜日 22:15',
      bg: 'bg-home-evening',
      showTransition: false,
      content: [
        { type: 'narration', text: '録音アプリを起動する。\n赤い録音ボタンを押してから、電話に出た。' },
        { type: 'text', speaker: '{name}', text: '……もしもし。' },
        { type: 'text', speaker: '佐藤', text: 'おう、{name}。夜遅くにすまんな。\n最近どうだ？色々大変だろう。' },
        { type: 'text', speaker: '佐藤', text: '田中のことは警察に任せておけ。\n余計なことに首を突っ込むなよ。\n会社のことは会社で処理する。' },
        { type: 'narration', text: '「余計なことに首を突っ込むな」。\n\nこれは忠告か。それとも脅しか。\n録音は続いている。' },
        { type: 'text', speaker: '{name}', text: 'はい…わかりました。' },
        { type: 'text', speaker: '佐藤', text: 'うん。まあ、しっかりやれよ。\nじゃあな。' },
        { type: 'narration', text: '通話が切れた。\n録音を確認する。\n\n佐藤の声は落ち着いていた。\n自信に満ちた声。\nそれが逆に不気味だ。' },
      ],
      next: 'ch2_scene5_noguchi',
    },

    // ===== 場面5：日曜深夜 — 野口との遭遇 =====
    ch2_scene5_noguchi: {
      location: '住宅街',
      time: '日曜日 23:30',
      bg: 'bg-night-street',
      content: [
        { type: 'narration', text: '佐藤の電話を切り、息を吐く。\n考えることが多すぎる。\n\n気分転換にコンビニまで歩くことにした。' },
        { type: 'narration', text: '夜の住宅街。\n自分の足音だけが響く静かな道。' },
        { type: 'narration', text: '……いや。\n足音がもう一つある。' },
        { type: 'sfx', name: 'footsteps' },
        { type: 'narration', text: '後ろを振り返る。\n暗がりに人影。\n\n距離を保ったまま、こちらについてくる。' },
        { type: 'effect', name: 'shake' },
        { type: 'narration', text: '佐藤の手の者か──！？\n\n歩調を速める。\n相手も速めてきた。' },
        { type: 'narration', text: '街灯の下まで走り、振り返った。' },
        { type: 'text', speaker: '{name}', text: '誰だ！' },
      ],
      choices: [
        {
          id: 'confront_noguchi',
          text: '立ち向かう',
          params: { boldness: 2 },
          next: 'ch2_scene5_noguchi_confront',
        },
        {
          id: 'calm_noguchi',
          text: '冷静に話しかける',
          params: { trust: 1 },
          next: 'ch2_scene5_noguchi_calm',
        },
        {
          id: 'run_noguchi',
          text: '走って逃げる',
          params: { suspicion: 1 },
          next: 'ch2_scene5_noguchi_run',
        },
      ],
      timeLimit: 8,
    },

    ch2_scene5_noguchi_confront: {
      location: '住宅街',
      time: '日曜日 23:35',
      bg: 'bg-night-danger',
      showTransition: false,
      content: [
        { type: 'narration', text: '拳を握り、相手に向かって一歩踏み出す。' },
        { type: 'text', speaker: '???', text: 'おっ……おい、落ち着け！' },
        { type: 'narration', text: '街灯に照らされた顔。\n30代後半の男。見覚えがある──' },
        { type: 'text', speaker: '野口', text: '殴るな殴るな！\n俺は野口だ。野口健二。\n□□商事の元社員だよ！' },
        { type: 'narration', text: '野口健二。\n半年前に解雇された元社員。\n田中が不正を内部通報した件の\n当事者だった男。' },
        { type: 'text', speaker: '{name}', text: '野口さん……？\nなぜこんな時間に尾行を。' },
        { type: 'text', speaker: '野口', text: 'お前に聞きたいことがあるんだ。\n田中のことだ。' },
      ],
      next: 'ch2_scene5_noguchi_talk',
    },

    ch2_scene5_noguchi_calm: {
      location: '住宅街',
      time: '日曜日 23:35',
      bg: 'bg-night-street',
      showTransition: false,
      content: [
        { type: 'text', speaker: '{name}', text: '……出てきてください。\n話があるなら聞きます。' },
        { type: 'narration', text: '影がゆっくりと近づいてくる。\n街灯に照らされた顔──' },
        { type: 'text', speaker: '野口', text: '……ふん。度胸あるな。' },
        { type: 'narration', text: '野口健二。\n半年前に解雇された元社員。\n田中が不正を内部通報した件の\n当事者だった男。' },
        { type: 'text', speaker: '野口', text: '俺は野口だ。覚えてるか？\n半年前にクビになった野口だよ。' },
        { type: 'text', speaker: '{name}', text: '……ええ。\nなぜ自分を尾行していたんですか。' },
        { type: 'text', speaker: '野口', text: '田中のことで話がある。\nだが普通に会いに行ける立場じゃねえだろ。\n解雇された人間がよ。' },
      ],
      next: 'ch2_scene5_noguchi_talk',
    },

    ch2_scene5_noguchi_run: {
      location: '住宅街',
      time: '日曜日 23:35',
      bg: 'bg-night-danger',
      showTransition: false,
      content: [
        { type: 'narration', text: '走った。全力で。\nだが相手も追ってくる。' },
        { type: 'text', speaker: '???', text: '待て！待ってくれ！\n話を聞いてくれ！' },
        { type: 'narration', text: '追手にしては妙だ。\n「待ってくれ」と叫んでいる。' },
        { type: 'narration', text: 'コンビニの明かりが見えた。\n店の前で立ち止まり、振り返る。' },
        { type: 'text', speaker: '野口', text: 'はあ……はあ……。\n逃げんなよ……話があるだけだ……。' },
        { type: 'narration', text: '息を切らした男が追いついてきた。\n街灯に照らされた顔──\n\n野口健二。\n半年前に解雇された元社員。' },
        { type: 'text', speaker: '野口', text: '俺は野口だ。\n田中のことで話がある。\n頼むから聞いてくれ。' },
      ],
      next: 'ch2_scene5_noguchi_talk',
    },

    ch2_scene5_noguchi_talk: {
      location: '住宅街',
      time: '日曜日 23:40',
      bg: 'bg-night-street',
      showTransition: false,
      content: [
        { type: 'text', speaker: '野口', text: '田中が死んだってニュースで見た。\n殺されたんだろ？' },
        { type: 'text', speaker: '{name}', text: '……それで、何が聞きたいんですか。' },
        { type: 'text', speaker: '野口', text: '俺は田中を恨んでた。\nあいつが通報したせいでクビになった。\n家族にも捨てられた。' },
        { type: 'narration', text: '野口の声に怒りが混じっている。\nだが同時に、何か別の感情も。' },
        { type: 'text', speaker: '野口', text: 'でもな。殺しちゃいねえよ。\n殺してやりたいと思ったことは\n何度もあったけどな。' },
        { type: 'text', speaker: '野口', text: '俺が言いたいのはそこじゃない。\n金曜の夜──事件があった夜。\n俺はこの近くにいたんだ。' },
        { type: 'sfx', name: 'tensionSting' },
        { type: 'text', speaker: '{name}', text: '……事件の夜に、ここに？' },
        { type: 'text', speaker: '野口', text: '元カノがこのマンションに住んでてな。\n復縁を迫りに……まあ、それはいい。' },
        { type: 'text', speaker: '野口', text: 'その時に見たんだ。\n田中のマンションに入っていく\nスーツ姿の男を。' },
        { type: 'effect', name: 'shake' },
      ],
      choices: [
        {
          id: 'ask_detail',
          text: 'その男の特徴を詳しく聞く',
          params: { investigation: 2 },
          flags: { noguchi_detailed: true },
          next: 'ch2_scene5_noguchi_detail',
        },
        {
          id: 'ask_threaten',
          text: '脅迫メールのことを問い詰める',
          params: { boldness: 1 },
          next: 'ch2_scene5_noguchi_threaten',
        },
        {
          id: 'ask_police',
          text: '警察には話したのか聞く',
          params: { trust: 1 },
          next: 'ch2_scene5_noguchi_police',
        },
      ],
    },

    ch2_scene5_noguchi_detail: {
      location: '住宅街',
      time: '日曜日 23:45',
      bg: 'bg-night-street',
      showTransition: false,
      content: [
        { type: 'text', speaker: '{name}', text: 'その男──どんな特徴でした？\n顔は見えましたか。' },
        { type: 'text', speaker: '野口', text: '暗かったから顔までは……。\nだが体格はしっかりしてた。\n170後半ぐらい。' },
        { type: 'text', speaker: '野口', text: '黒いスーツにネクタイ。\nあと……甘い匂いがした。\n高そうなコロンだ。すれ違った時にな。' },
        { type: 'narration', text: '甘い香水の匂い。\n高級コロン。\n\n……どこかで聞いた特徴だ。' },
        { type: 'text', speaker: '野口', text: 'そいつ、田中の部屋に入る時\n鍵を使ってたぞ。\n合鍵か何か持ってるみたいだった。' },
        { type: 'sfx', name: 'tensionSting' },
        {
          type: 'evidence',
          id: 'noguchi_witness',
          name: '野口の目撃証言',
          description: '事件当夜、田中のマンションに入るスーツ姿の男を目撃。170後半、甘い香水、鍵を使って入室。',
        },
        { type: 'narration', text: '重要な証言だ。\n犯人は田中の部屋の鍵を持っていた。\nそして甘い香水をつけていた。' },
      ],
      next: 'ch2_scene5_noguchi_end',
    },

    ch2_scene5_noguchi_threaten: {
      location: '住宅街',
      time: '日曜日 23:45',
      bg: 'bg-night-street',
      showTransition: false,
      content: [
        { type: 'text', speaker: '{name}', text: '野口さん。\n田中に脅迫メールを送っていましたよね。' },
        { type: 'effect', name: 'shake' },
        { type: 'text', speaker: '野口', text: '……！\nなぜそれを……。' },
        { type: 'text', speaker: '{name}', text: 'データに残っていました。\n「お前のせいで人生を壊された。\n覚えていろ」。' },
        { type: 'text', speaker: '野口', text: '……ああ、送った。\n酔った勢いでな。\nだがそれだけだ。実際には何もしてねえ。' },
        { type: 'text', speaker: '野口', text: '信じなくてもいい。\nだが俺は見たんだ。\nあの夜、スーツの男が田中の部屋に入っていくのを。' },
        { type: 'text', speaker: '野口', text: '背の高い男だった。\n170後半。甘い匂いがした。\n鍵を使って部屋に入っていった。' },
        {
          type: 'evidence',
          id: 'noguchi_witness',
          name: '野口の目撃証言',
          description: '事件当夜、田中のマンションに入るスーツ姿の男を目撃。170後半、甘い香水、鍵を使って入室。',
        },
        { type: 'narration', text: '脅迫メールの件は認めた。\nだが目撃証言も得られた。\n犯人は鍵を持っていた。' },
      ],
      next: 'ch2_scene5_noguchi_end',
    },

    ch2_scene5_noguchi_police: {
      location: '住宅街',
      time: '日曜日 23:45',
      bg: 'bg-night-street',
      showTransition: false,
      content: [
        { type: 'text', speaker: '{name}', text: 'その話、警察にはしたんですか。' },
        { type: 'text', speaker: '野口', text: '警察？冗談だろ。\n俺みたいな立場の人間が警察に行ったら\n逆に疑われるに決まってる。' },
        { type: 'text', speaker: '野口', text: '解雇された元社員が\n事件の夜に現場近くにいました、なんて\n言えるわけねえだろ。' },
        { type: 'narration', text: '野口の言い分にも一理ある。\n元社員が事件現場の近くにいたとなれば\n真っ先に疑われるだろう。' },
        { type: 'text', speaker: '野口', text: 'だからお前に話しに来たんだ。\n田中と同じ部署の人間なら\n何か心当たりがあるんじゃないか。' },
        { type: 'text', speaker: '野口', text: 'スーツの男。背は170後半。\n甘い匂い──高そうなコロン。\nそいつは鍵を持ってた。合鍵だろうな。' },
        {
          type: 'evidence',
          id: 'noguchi_witness',
          name: '野口の目撃証言',
          description: '事件当夜、田中のマンションに入るスーツ姿の男を目撃。170後半、甘い香水、鍵を使って入室。',
        },
        { type: 'narration', text: '野口からの目撃証言。\n犯人は田中の部屋の合鍵を持っていた。' },
      ],
      next: 'ch2_scene5_noguchi_end',
    },

    ch2_scene5_noguchi_end: {
      location: '住宅街',
      time: '日曜日 23:55',
      bg: 'bg-night-street',
      showTransition: false,
      content: [
        { type: 'text', speaker: '野口', text: '俺の話は以上だ。\n信じるも信じないも勝手にしろ。' },
        { type: 'text', speaker: '野口', text: '……一つだけ言っておく。\n田中を恨んでたのは事実だ。\nだが殺してはいない。' },
        { type: 'text', speaker: '野口', text: 'あいつは……間違ったことはしてなかった。\n俺が不正をしていたのは事実だからな。' },
        { type: 'narration', text: '野口は背を向けて歩き去った。\n\n複雑な男だ。\n恨みを抱えながらも\n自分の非は認めている。' },
        { type: 'narration', text: '自宅に戻る。\n頭の中で情報を整理する。' },
      ],
      next: 'ch2_scene6_ending',
    },

    // ===== 場面6：第2章エンディング =====
    ch2_scene6_ending: {
      location: '自宅',
      time: '月曜日 0:30',
      effect: 'fadeIn',
      bg: 'bg-home-evening',
      content: [
        { type: 'narration', text: '深夜。眠れない。\n\n整理しよう。今日わかったことを。' },
        { type: 'narration', text: '佐藤は7000万円を横領していた。\n田中がそれを発見し、口封じに殺された可能性が高い。' },
        { type: 'narration', text: '鈴木によると、田中には最近\n女性の訪問者がいた。' },
        { type: 'narration', text: '田中のUSBに残された日記。\n「中村さんを巻き込めない」\n「すべてが終わったら話す」\n\n中村とは誰だ。' },
        { type: 'narration', text: '野口が目撃した犯人像。\nスーツの男。甘い香水。\nそして──田中の部屋の合鍵を持っていた。' },
        { type: 'narration', text: '合鍵。\n犯人は田中と極めて近しい人間。\n鍵を渡されるほどの関係。\n\n……恋人か？' },
        { type: 'sfx', name: 'phoneRing' },
        {
          type: 'notification',
          title: '差出人不明',
          text: '中村に聞け',
        },
        { type: 'effect', name: 'shake' },
        { type: 'narration', text: 'まただ。差出人不明のメッセージ。\n\n「中村に聞け」\n\n田中の日記にあった「中村さん」と\n同じ人物だろうか。' },
        { type: 'narration', text: '中村。\n社内にその名前の人間はいるか──\n\n……いる。\n別の部署に中村綾という女性がいる。' },
        { type: 'narration', text: '明日、中村を探す。\nそして黒田にも会わなければ。\n\n事件は予想以上に深い。\n容疑者は一人ではないのかもしれない。' },
        { type: 'narration', text: '\n　　　　　── 第2章 終 ──' },
      ],
      choices: [
        {
          id: 'to_ch3',
          text: '第3章へ進む',
          next: 'ch3_scene1',
        },
      ],
    },
  },
};
